application:
    SESSION_SECRET: 
    ServiceToken: 
    settings:
        logs: 
            level: debug
        redis:
            url: redis://127.0.0.1:6380/0
        auth0:
            AUTH0_DOMAIN: ic-travel.eu.auth0.com
            AUTH0_CLIENT_ID: 
            AUTH0_CLIENT_SECRET: 
            AUTH0_CALLBACK: http://localhost:5050/auth/callback
